
//! Autogenerated weights for `pallet_nft_currency`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-08-28, STEPS: `1`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `demo`, CPU: `11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_nft_currency
// --extrinsic
// *
// --repeat
// 20
// --output
// weight.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_nft_currency`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_nft_currency::WeightInfo for WeightInfo<T> {
	// Storage: NftCurrencyPallet TotalTokens (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: NftCurrencyPallet TokenOwner (r:1 w:1)
	// Storage: NftCurrencyPallet OwnerToken (r:1 w:1)
	fn mint_token() -> Weight {
		(42_776_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: NftCurrencyPallet TokenOwner (r:1 w:1)
	// Storage: NftCurrencyPallet OwnerToken (r:2 w:2)
	fn transfer_token() -> Weight {
		(49_895_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: NftCurrencyPallet TokenOwner (r:1 w:1)
	// Storage: NftCurrencyPallet Approval (r:1 w:0)
	// Storage: NftCurrencyPallet OwnerToken (r:2 w:2)
	fn safe_transfer() -> Weight {
		(54_275_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: NftCurrencyPallet TokenOwner (r:1 w:0)
	// Storage: NftCurrencyPallet TokenApproval (r:1 w:1)
	fn approve() -> Weight {
		(38_030_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: NftCurrencyPallet Approval (r:1 w:1)
	fn approve_for_all() -> Weight {
		(26_615_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: NftCurrencyPallet TokenOwner (r:1 w:0)
	// Storage: NftCurrencyPallet TokenUri (r:1 w:1)
	fn set_token_uri() -> Weight {
		(17_653_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
